# Generated by Django 5.1.7 on 2025-03-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormLogin',
            new_name='FormsLogin',
        ),
    ]
