# Generated by Django 5.1.7 on 2025-03-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_studio', '0002_rename_formlogin_formslogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormsLogin',
        ),
    ]
