# Generated by Django 5.1.7 on 2025-03-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_studio', '0005_delete_formslogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
