# Generated by Django 5.1.7 on 2025-03-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_studio', '0007_shedulingmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShedulingModel',
            new_name='SchedulingModel',
        ),
    ]
