# Generated by Django 5.1.7 on 2025-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_studio', '0008_rename_shedulingmodel_schedulingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingmodel',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulingmodel',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
